# Generated by Django 5.0.6 on 2024-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediCare_app', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='Document',
            field=models.ImageField(upload_to='doctor'),
        ),
    ]
